### ISSUE TITLE
Editor Improvements

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Nitro-Web#198]
Improve the Editor usage:

**Todo`s:**
- [x] edit posts
- [ ] create posts
  - [x] title
  - [x] content
  - [ ] tags
  - [ ] categories
- [ ] fix broken integration test as now you cant report your own contributions or your self as a user
- [x] always add `target="_blank"` to the rendered links
- [ ] render all content with the editor-content component
- [ ] **Stylings**
  - [x] bold
  - [x] italic
  - [ ] strike
- [ ] **Elements**
  - [x] links
